// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Removed import of firebase_core due to missing package; using local FirebaseOptions class instead.
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ_Herbjeu9X8rKRUzauctl8NwJWaxH04',
    appId: '1:1074201162635:web:5c05564c6215d3f7b0b58e',
    messagingSenderId: '1074201162635',
    projectId: 'registroponto-8f04c',
    authDomain: 'registroponto-8f04c.firebaseapp.com',
    storageBucket: 'registroponto-8f04c.appspot.com',
    measurementId: 'G-G3ZRBGQ4D1', iosBundleId: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBLmtTcQGXNzFy-kagWxHPWkg6DChFgwk',
    appId: '1:1074201162635:android:651f417879653a1cb0b58e',
    messagingSenderId: '1074201162635',
    projectId: 'registroponto-8f04c',
    storageBucket: 'registroponto-8f04c.appspot.com', iosBundleId: '', authDomain: '', measurementId: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWPU8V-yQxr35z1v8G-8GEJagTU7VJG6I',
    appId: '1:1074201162635:ios:cfc8c9ce9e21d3b8b0b58e',
    messagingSenderId: '1074201162635',
    projectId: 'registroponto-8f04c',
    storageBucket: 'registroponto-8f04c.appspot.com',
    iosBundleId: 'com.example.registroPonto', authDomain: '', measurementId: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWPU8V-yQxr35z1v8G-8GEJagTU7VJG6I',
    appId: '1:1074201162635:ios:cfc8c9ce9e21d3b8b0b58e',
    messagingSenderId: '1074201162635',
    projectId: 'registroponto-8f04c',
    storageBucket: 'registroponto-8f04c.appspot.com',
    iosBundleId: 'com.example.registroPonto', authDomain: '', measurementId: '',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ_Herbjeu9X8rKRUzauctl8NwJWaxH04',
    appId: '1:1074201162635:web:5e2a812a67f9f17db0b58e',
    messagingSenderId: '1074201162635',
    projectId: 'registroponto-8f04c',
    authDomain: 'registroponto-8f04c.firebaseapp.com',
    storageBucket: 'registroponto-8f04c.appspot.com',
    measurementId: 'G-DRX0H2F7NQ', iosBundleId: '',
  );
}

class FirebaseOptions {
  const FirebaseOptions({required String apiKey, required String appId, required String messagingSenderId, required String projectId, required String storageBucket, required String iosBundleId, required String authDomain, required String measurementId});
}
